In [2]:
import pandas as pd
import numpy as np

In [2]:
# A numpy array
arr = np.random.randn(4) # random values from std normal distribution
print(type(arr))
print(arr, "\n")

# A pandas series made from the previous array
s = pd.Series(arr)
print(type(s))
print(s)

<class 'numpy.ndarray'>
[-0.41595367 -0.18387136  0.33775513 -0.41025236]

<class 'pandas.core.series.Series'>
0   -0.415954
1   -0.183871
2    0.337755
3   -0.410252
dtype: float64

In [4]:
# A series from a list of strings with default index
pd.Series(['EDS 220', 'EDS 222', 'EDS 223', 'EDS 242'])

0    EDS 220
1    EDS 222
2    EDS 223
3    EDS 242
dtype: object

In [5]:
# Construct dictionary
d = {'key_0':2, 'key_1':'3', 'key_2':5}

# Initialize series using a dictionary
pd.Series(d)

key_0    2
key_1    3
key_2    5
dtype: object

In [13]:
pd.Series(3.0, index = ['A', 'B', 'C'])

A    3.0
B    3.0
C    3.0
dtype: float64

In [6]:
# Define a series
s = pd.Series([98,73,65],index=['Andrea', 'Beth', 'Carolina'])
print(s)
# Divide each element in series by 10
print(s /10, '\n')

# Take the exponential of each element in series
print(np.exp(s), '\n')

# Original series is unchanged
print(s)

Andrea      98
Beth        73
Carolina    65
dtype: int64
Andrea      9.8
Beth        7.3
Carolina    6.5
dtype: float64

Andrea      3.637971e+42
Beth        5.052394e+31
Carolina    1.694889e+28
dtype: float64

Andrea      98
Beth        73
Carolina    65
dtype: int64

In [7]:
s > 70

Andrea       True
Beth         True
Carolina    False
dtype: bool

In [8]:
# Series with NAs in it
s = pd.Series([1, 2, np.nan, 4, np.nan])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [9]:
s.hasnans

True

In [15]:
s.isna().count()

5

In [22]:
s = pd.Series([5, -999, 2, -999], index=['A', 'B', 'C', 'D'])
s

A      5
B   -999
C      2
D   -999
dtype: int64

In [25]:
s.mask(s==-999)

A    5.0
B    NaN
C    2.0
D    NaN
dtype: float64

In [3]:
# Initialize dictionary with columns' data 
d = {'col_name_1' : pd.Series(np.arange(3)),
     'col_name_2' : pd.Series([3.1, 3.2, 3.3]),
     }

# Create data frame
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [4]:
df.index=[1,2,3]
df

   col_name_1  col_name_2
1           0         3.1
2           1         3.2
3           2         3.3

In [5]:
df.columns = ['Col 1', 'col_name_2']

In [10]:
df

   Col 1  col_name_2
1      0         3.1
2      1         3.2
3      2         3.3

In [6]:
df = df.rename(columns={'col_name_2': 'Col 2'})

In [12]:
df

   Col 1  Col 2
1      0    3.1
2      1    3.2
3      2    3.3

In [7]:
df.set_index('Col 1')

       Col 2
Col 1
0        3.1
1        3.2
2        3.3